### PR TITLE
Expand language of the charter

### PR DESCRIPTION
**Pull request by ebahapo**
Expand language to include any kind of partners, commercial or not, per discussion in the meeting on 2020/12/17.

I believe that such a minor change in language would be sufficient to expand the charter to all kinds of partners, albeit maintaining the desire to foster commercial partners.

### CODE REVIEW

**Comment by jeremybennett** [comment]
Hi @ebahapo This misses the point of the objective. We are trying to address a specific problem, the lack of a commercial ecosystem for RISC-V software tools.

If you are concerned that RISC-V software tools are not getting the exposure in the academic world, then we can add a new goal to develop this. Although I am not convinced this is a problem. The group's chair (me) is a former academic, the co-chair (@lazyparser) is Director of a major academic group and our first project is led from PLCT at the Chinese Academy of Sciences.

**Comment by ebahapo** [comment]
@jeremybennett, my concern is that I do not believe that the lack of a commercial ecosystem is a specific problem for that this Code Speed Optimization SIG should address.  

I appreciate this desire and welcome companies willing to throw their hat at RISC-V, but perhaps an active effort towards that would deserve its own SIG.

**Comment by lazyparser** [comment]
Hi @ebahapo @jeremybennett 

Since the group had been merged into code size, this PR seems irrelevant now.

Should we close this Pull Request?

**Comment by lazyparser** [comment]
Since the code speed SIG had been merged into Code Opt Group, This issue is no longer relevant. Close it for now.

**Pull request closed without merging**
