### PR TITLE
Add participate info

### PR DESCRIPTION
**Pull request by pz9115**
Add participate info with "Exposing SImode operations to the RTL expanders for `any_bitwise` on RV64" optimate.

### CODE REVIEW

**Comment by jeremybennett** [comment]
Hi @pz9115 

Great idea to have a record of who is working on each project.  However I'm not sure whether this is the right way.  What we need to know is:

1. who is working on the project; and
2. how to contact them.

The first is important to avoid duplicating effort, the second is important so that others can reach out to collaborate with you. It could be an email address, or a GitHub ID, or something similar.

The question is where we put this information. The problem with a project document is that it is quite static, and not a good place to discuss progress. Perhaps it would be a good idea to have a GitHub issue associated with each optimization. Then the document could refer to the GitHub issue, which would be the forum for discussion. This also solve the problem of how to contact the person working on the project - it is in the GitHub issue.  Do you think this would be a good approach?

I look forward to your thoughts on this.

**Comment by pz9115** [comment]
Hi Jeremy,

I think we can establish a list file to maintain the status of each project.

The list file may record project name, project partner, how to contact（like email or GitHub ID）, and a current respository (both individual or team or a new branch or just a link)，the status of project. More details will record in sublinks. It is good for people who want to join it . 

Thank you for your recommendation.

**Comment by lazyparser** [comment]
Do we have some progress here?

**Comment by lazyparser** [comment]
Since the code speed SIG had been merged into Code Opt Group, This issue is no longer relevant. Close it for now.

**Pull request closed without merging**
